### ISSUE TITLE
Auth is no longer required.

### ISSUE THREAD

**Issue by ShuffleBit** [NovaGL/HarmonyHubControl#8] opened 2018-12-24 16:40 UTC
With Logitech's release of "developer" firmware, it is neither necessary nor even possible to get an authentication token. The hub is fully accessible to anything on its LAN.

Skip all the authentication stuff, and it works. Kind of.

This was their answer to DIY'ers pushback when they disabled XMPP for "security reasons" (remove any/all security). It still breaks all the automation stuff that jumped their old authentication hurdles That sounds passive-aggressive to me.

The more I fiddle with Logitech's harebrained crap, the better a $199 NEEO "Brain" looks... Yes, I said it: "harebrained". Logitech's team have brains that are roughly equivalent to a hare's. Small, slow, extremely limited, geared toward massive procreation vs quality, destined to be another virtual pile of frozen coyote dung in the annals of computing history.

**Comment by NovaGL** [comment] 2018-12-26 05:34
Is there a question here, or is this informational only. I'm currently not maintaining this repo, feel free to do a PR though.

**Comment by NovaGL** [comment] 2018-12-26 05:38
Duplicate of #5

**Closed as completed by NovaGL** 2018-12-26 05:38 UTC
Labels: duplicate
